# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a1561230884b028193ff6dd66b4e0947545ad988a9a9dc2f3f7c57f536a0e040f9ca8181703ffd40184b4a229d0d266e1298ea0b28c8227d69d5db72cd3a5a4

test:
  secret_key_base: badb8cd051ac832bf898b0c63f8aa708001fe209f3ddc42ebcd3c8da3bf69a7f2f5c0fc9a4642c0151b62df1dc3b64a8be436aa10834ff922c860d683716c68d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
